# -*- coding: utf-8 -*-
"""traffic_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEmLGoPeTlLr6eQCv-NMTBkaHbrbhHgZ
"""

!pip install ultralytics opencv-python easyocr gradio

from ultralytics import YOLO
import cv2
import easyocr
from google.colab.patches import cv2_imshow

model = YOLO("yolov8s.pt")   # object detection
reader = easyocr.Reader(['en'])  # OCR

!unzip /content/drive/MyDrive/Helmet\ Detection\ Project.yolov8.zip -d /content/drive/MyDrive/dataset

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/drive/MyDrive/dataset/data.yaml
# train: /content/drive/MyDrive/dataset/train/images
# val: /content/drive/MyDrive/dataset/train/images
# 
# nc: 3
# names: ['helmet', 'license_plate', 'motorcyclist']

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/drive/MyDrive/dataset/data.yaml",
    epochs=5,
    imgsz=640
)

helmet_model = YOLO("/content/drive/MyDrive/best.pt")

helmet_model.names  # run this to see all classes

# Yours likely outputs something like:
# {0: 'helmet', 1: 'license_plate', 2: 'motorcyclist'}

from ultralytics import YOLO
result=helmet_model("/content/drive/MyDrive/dataset/train/images/sample.jpg", show=True)
annotated = result[0].plot()

from google.colab.patches import cv2_imshow
cv2_imshow(annotated)

video_path = "/content/drive/MyDrive/traffic1.mp4"

import os
print(os.path.exists(video_path))

!ls /content/drive/Mydriv

!du -h /content/output.mp4

!pip install  requests

#extract clear frames from your video
import cv2
import os

cap = cv2.VideoCapture("/content/drive/MyDrive/traffic2.mp4")
os.makedirs("/content/drive/MyDrive/test_images", exist_ok=True)

frame_count = 0
saved_count = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1

    # Save every 30th frame (1 per second approx)
    if frame_count % 60 == 0:
        path = f"/content/drive/MyDrive/test_images/image_{frame_count}.jpg"
        cv2.imwrite(path, frame)
        saved_count += 1

cap.release()
print(f"Saved {saved_count} frames")

# Cell 1 — all the code above
# Cell 2 — extract frames from video
# Cell 3 — test single image
img = cv2.imread("/content/drive/MyDrive/test_images/image_105.jpg")
result, violations = process_image(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
cv2_imshow(cv2.cvtColor(result, cv2.COLOR_RGB2BGR))
print(violations)

"""code without ocr"""

import cv2
import numpy as np
import os
import datetime
from ultralytics import YOLO


# -------- FOLDERS --------
os.makedirs("/content/drive/MyDrive/violations/no_helmet", exist_ok=True)
os.makedirs("/content/drive/MyDrive/violations/triple_riding", exist_ok=True)

violation_count = 0

# ---------------- HELMET MATCHING ----------------
def helmet_on_rider(rider, helmets):
    rx1, ry1, rx2, ry2 = rider
    head_box = (rx1, ry1, rx2, ry1 + int((ry2 - ry1) * 0.35))
    for hx1, hy1, hx2, hy2 in helmets:
        hcx = (hx1 + hx2) // 2
        hcy = (hy1 + hy2) // 2
        if (head_box[0] <= hcx <= head_box[2]) and (head_box[1] <= hcy <= head_box[3]):
            return True
    return False

# ---------------- HELPERS ----------------
def get_center(box):
    x1, y1, x2, y2 = box
    return ((x1 + x2) // 2, (y1 + y2) // 2)

def is_near(box1, box2, threshold=100):
    cx1, cy1 = get_center(box1)
    cx2, cy2 = get_center(box2)
    return abs(cx1 - cx2) < threshold and abs(cy1 - cy2) < threshold

def rider_has_plate(rider, plate):
    rx1, ry1, rx2, ry2 = rider
    px1, py1, px2, py2 = plate
    pcx = (px1 + px2) // 2
    horizontally_inside = (rx1 - 30) <= pcx <= (rx2 + 30)
    rider_middle = ry1 + (ry2 - ry1) // 2
    vertically_in_bottom = py1 >= rider_middle
    return horizontally_inside and vertically_in_bottom

def save_violation(frame, rider_box, plate_box, violation_type, frame_count):
    """
    Saves two images:
    1. Full frame with violation highlighted
    2. Plate crop (if available)
    """
    global violation_count
    violation_count += 1

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    folder = f"/content/drive/MyDrive/violations/{violation_type}"

    rx1, ry1, rx2, ry2 = rider_box

    #Save full frame with box
    frame_copy = frame.copy()
    cv2.rectangle(frame_copy, (rx1, ry1), (rx2, ry2), (0, 0, 255), 3)
    cv2.putText(frame_copy, violation_type.upper().replace("_", " "),
                (rx1, ry1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 255), 2)

    frame_path = f"{folder}/frame_{frame_count}_{timestamp}.jpg"
    cv2.imwrite(frame_path, frame_copy)
    print(f"Saved full frame: {frame_path}")

    #save the plate if exits
    if plate_box:
        px1, py1, px2, py2 = plate_box

        pad_y = max(40, int((py2 - py1) * 0.5))
        pad_x = max(20, int((px2 - px1) * 0.2))
        py1_p = max(0, py1 - pad_y)
        py2_p = min(frame.shape[0], py2 + pad_y)
        px1_p = max(0, px1 - pad_x)
        px2_p = min(frame.shape[1], px2 + pad_x)

        plate_crop = frame[py1_p:py2_p, px1_p:px2_p]

        if plate_crop.size > 0:
            plate_path = f"{folder}/plate_{frame_count}_{timestamp}.jpg"
            cv2.imwrite(plate_path, plate_crop)
            print(f"Saved plate crop: {plate_path}")


cap = cv2.VideoCapture("/content/drive/MyDrive/traffic2.mp4")#video

if not cap.isOpened():
    print("Error: Could not open video.")
    exit()

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps    = cap.get(cv2.CAP_PROP_FPS)
if fps == 0:
    fps = 30

out = cv2.VideoWriter(
    "/content/output.mp4",
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps,
    (width, height)
)

frame_count = 0

# To avoid saving same violation every frame
saved_keys = set()

# ---------------- MAIN LOOP ----------------
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    helmets, plates, riders = [], [], []

    # DETECTIONS
    results = helmet_model(frame, imgsz=640)
    for box in results[0].boxes:
        cls = int(box.cls[0])
        label = helmet_model.names[cls]
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        if label == "helmet":
            helmets.append((x1, y1, x2, y2))
        elif label == "license_plate":
            plates.append((x1, y1, x2, y2))
        elif label == "motorcyclist":
            riders.append((x1, y1, x2, y2))

    # GROUP RIDERS
    groups = []
    for rider in riders:
        placed = False
        for group in groups:
            if any(is_near(rider, r) for r in group):
                group.append(rider)
                placed = True
                break
        if not placed:
            groups.append([rider])

    # PROCESS
    for group in groups:

        # TRIPLE RIDING
        if len(group) >= 3:
            for rider in group:
                x1, y1, x2, y2 = rider
                cv2.rectangle(frame, (x1,y1),(x2,y2),(0,0,255),2)
                cv2.putText(frame, "TRIPLE RIDING", (x1, y1-30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,0,255), 2)

            # Save once per group per 30 frames
            group_key = (tuple(group[0]), "triple")
            if group_key not in saved_keys or frame_count % 30 == 0:
                saved_keys.add(group_key)

                # Find plate for first rider in group
                nearby_plates = [p for p in plates if rider_has_plate(group[0], p)]
                plate_box = nearby_plates[0] if nearby_plates else None

                save_violation(frame, group[0], plate_box, "triple_riding", frame_count)

        # HELMET CHECK
        for rider in group:
            rx1, ry1, rx2, ry2 = rider
            has_helm = helmet_on_rider(rider, helmets)

            if not has_helm:
                cv2.rectangle(frame, (rx1,ry1),(rx2,ry2),(0,0,255),2)
                cv2.putText(frame, "NO HELMET", (rx1, ry1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,0,255), 2)

                nearby_plates = [p for p in plates if rider_has_plate(rider, p)]

                if nearby_plates:
                    px1, py1, px2, py2 = nearby_plates[0]
                    cv2.rectangle(frame, (px1,py1),(px2,py2),(255,255,0),2)
                    cv2.putText(frame, "PLATE", (px1, py1-10),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,0), 2)

                # Save once per rider per 30 frames
                rider_key = ((rx1//50, ry1//50), "helmet")
                if rider_key not in saved_keys or frame_count % 80 == 0:
                    saved_keys.add(rider_key)
                    plate_box = nearby_plates[0] if nearby_plates else None
                    save_violation(frame, rider, plate_box, "no_helmet", frame_count)

            else:
                cv2.rectangle(frame, (rx1,ry1),(rx2,ry2),(0,255,0),2)
                cv2.putText(frame, "HELMET", (rx1, ry1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)

    out.write(frame)

    if frame_count % 50 == 0:
        print(f"Processed {frame_count} frames | Violations saved: {violation_count}")

cap.release()
out.release()

print(f"\nDone! Total frames: {frame_count}")
print(f"Total violations saved: {violation_count}")
print(f"Check /content/violations/ folder")

